export const countryCallingCodes = [
  { country: "Mexico", iso3: "MEX", code: "+52" },

  { country: "Afghanistan", iso3: "AFG", code: "+93" },
  { country: "Albania", iso3: "ALB", code: "+355" },
  { country: "Algeria", iso3: "DZA", code: "+213" },
  { country: "Andorra", iso3: "AND", code: "+376" },
  { country: "Angola", iso3: "AGO", code: "+244" },
  { country: "Antarctica", iso3: "ATA", code: "+672" },
  { country: "Argentina", iso3: "ARG", code: "+54" },
  { country: "Armenia", iso3: "ARM", code: "+374" },
  { country: "Aruba", iso3: "ABW", code: "+297" },
  { country: "Australia", iso3: "AUS", code: "+61" },
  { country: "Austria", iso3: "AUT", code: "+43" },
  { country: "Azerbaijan", iso3: "AZE", code: "+994" },

  { country: "Bahrain", iso3: "BHR", code: "+973" },
  { country: "Bangladesh", iso3: "BGD", code: "+880" },
  { country: "Belarus", iso3: "BLR", code: "+375" },
  { country: "Belgium", iso3: "BEL", code: "+32" },
  { country: "Belize", iso3: "BLZ", code: "+501" },
  { country: "Benin", iso3: "BEN", code: "+229" },
  { country: "Bhutan", iso3: "BTN", code: "+975" },
  { country: "Bolivia", iso3: "BOL", code: "+591" },
  { country: "Bosnia and Herzegovina", iso3: "BIH", code: "+387" },
  { country: "Botswana", iso3: "BWA", code: "+267" },
  { country: "Brazil", iso3: "BRA", code: "+55" },
  { country: "Brunei", iso3: "BRN", code: "+673" },
  { country: "Bulgaria", iso3: "BGR", code: "+359" },
  { country: "Burkina Faso", iso3: "BFA", code: "+226" },
  { country: "Burundi", iso3: "BDI", code: "+257" },

  { country: "Cambodia", iso3: "KHM", code: "+855" },
  { country: "Cameroon", iso3: "CMR", code: "+237" },
  { country: "Canada", iso3: "CAN", code: "+1" },
  { country: "Cape Verde", iso3: "CPV", code: "+238" },
  { country: "Central African Republic", iso3: "CAF", code: "+236" },
  { country: "Chad", iso3: "TCD", code: "+235" },
  { country: "Chile", iso3: "CHL", code: "+56" },
  { country: "China", iso3: "CHN", code: "+86" },
  { country: "Colombia", iso3: "COL", code: "+57" },
  { country: "Comoros", iso3: "COM", code: "+269" },
  { country: "Congo, Republic of", iso3: "COG", code: "+242" },
  { country: "Congo, DR", iso3: "COD", code: "+243" },
  { country: "Costa Rica", iso3: "CRI", code: "+506" },
  { country: "Côte d'Ivoire", iso3: "CIV", code: "+225" },
  { country: "Croatia", iso3: "HRV", code: "+385" },
  { country: "Cuba", iso3: "CUB", code: "+53" },
  { country: "Curacao", iso3: "CUW", code: "+599" },
  { country: "Cyprus", iso3: "CYP", code: "+357" },
  { country: "Czech Republic", iso3: "CZE", code: "+420" },

  { country: "Denmark", iso3: "DNK", code: "+45" },
  { country: "Djibouti", iso3: "DJI", code: "+253" },

  { country: "Ecuador", iso3: "ECU", code: "+593" },
  { country: "Egypt", iso3: "EGY", code: "+20" },
  { country: "El Salvador", iso3: "SLV", code: "+503" },
  { country: "Equatorial Guinea", iso3: "GNQ", code: "+240" },
  { country: "Eritrea", iso3: "ERI", code: "+291" },
  { country: "Estonia", iso3: "EST", code: "+372" },
  { country: "Eswatini", iso3: "SWZ", code: "+268" },
  { country: "Ethiopia", iso3: "ETH", code: "+251" },

  { country: "Fiji", iso3: "FJI", code: "+679" },
  { country: "Finland", iso3: "FIN", code: "+358" },
  { country: "France", iso3: "FRA", code: "+33" },

  { country: "Gabon", iso3: "GAB", code: "+241" },
  { country: "Gambia", iso3: "GMB", code: "+220" },
  { country: "Georgia", iso3: "GEO", code: "+995" },
  { country: "Germany", iso3: "DEU", code: "+49" },
  { country: "Ghana", iso3: "GHA", code: "+233" },
  { country: "Greece", iso3: "GRC", code: "+30" },
  { country: "Greenland", iso3: "GRL", code: "+299" },
  { country: "Guatemala", iso3: "GTM", code: "+502" },
  { country: "Guinea", iso3: "GIN", code: "+224" },
  { country: "Guinea-Bissau", iso3: "GNB", code: "+245" },
  { country: "Guyana", iso3: "GUY", code: "+592" },

  { country: "Haiti", iso3: "HTI", code: "+509" },
  { country: "Honduras", iso3: "HND", code: "+504" },
  { country: "Hungary", iso3: "HUN", code: "+36" },

  { country: "Iceland", iso3: "ISL", code: "+354" },
  { country: "India", iso3: "IND", code: "+91" },
  { country: "Indonesia", iso3: "IDN", code: "+62" },
  { country: "Iran", iso3: "IRN", code: "+98" },
  { country: "Iraq", iso3: "IRQ", code: "+964" },
  { country: "Ireland", iso3: "IRL", code: "+353" },
  { country: "Israel", iso3: "ISR", code: "+972" },
  { country: "Italy", iso3: "ITA", code: "+39" },

  { country: "Jamaica", iso3: "JAM", code: "+1" },
  { country: "Japan", iso3: "JPN", code: "+81" },
  { country: "Jordan", iso3: "JOR", code: "+962" },

  { country: "Kazakhstan", iso3: "KAZ", code: "+7" },
  { country: "Kenya", iso3: "KEN", code: "+254" },
  { country: "Kuwait", iso3: "KWT", code: "+965" },
  { country: "Kyrgyzstan", iso3: "KGZ", code: "+996" },

  { country: "Laos", iso3: "LAO", code: "+856" },
  { country: "Latvia", iso3: "LVA", code: "+371" },
  { country: "Lebanon", iso3: "LBN", code: "+961" },
  { country: "Lesotho", iso3: "LSO", code: "+266" },
  { country: "Liberia", iso3: "LBR", code: "+231" },
  { country: "Libya", iso3: "LBY", code: "+218" },
  { country: "Liechtenstein", iso3: "LIE", code: "+423" },
  { country: "Lithuania", iso3: "LTU", code: "+370" },
  { country: "Luxembourg", iso3: "LUX", code: "+352" },

  { country: "Madagascar", iso3: "MDG", code: "+261" },
  { country: "Malawi", iso3: "MWI", code: "+265" },
  { country: "Malaysia", iso3: "MYS", code: "+60" },
  { country: "Maldives", iso3: "MDV", code: "+960" },
  { country: "Mali", iso3: "MLI", code: "+223" },
  { country: "Malta", iso3: "MLT", code: "+356" },
  { country: "Mauritania", iso3: "MRT", code: "+222" },
  { country: "Mauritius", iso3: "MUS", code: "+230" },
  { country: "Moldova", iso3: "MDA", code: "+373" },
  { country: "Monaco", iso3: "MCO", code: "+377" },
  { country: "Mongolia", iso3: "MNG", code: "+976" },
  { country: "Montenegro", iso3: "MNE", code: "+382" },
  { country: "Morocco", iso3: "MAR", code: "+212" },
  { country: "Mozambique", iso3: "MOZ", code: "+258" },
  { country: "Myanmar", iso3: "MMR", code: "+95" },

  { country: "Namibia", iso3: "NAM", code: "+264" },
  { country: "Nepal", iso3: "NPL", code: "+977" },
  { country: "Netherlands", iso3: "NLD", code: "+31" },
  { country: "New Zealand", iso3: "NZL", code: "+64" },
  { country: "Nicaragua", iso3: "NIC", code: "+505" },
  { country: "Niger", iso3: "NER", code: "+227" },
  { country: "Nigeria", iso3: "NGA", code: "+234" },
  { country: "North Korea", iso3: "PRK", code: "+850" },
  { country: "North Macedonia", iso3: "MKD", code: "+389" },
  { country: "Norway", iso3: "NOR", code: "+47" },

  { country: "Oman", iso3: "OMN", code: "+968" },

  { country: "Pakistan", iso3: "PAK", code: "+92" },
  { country: "Panama", iso3: "PAN", code: "+507" },
  { country: "Paraguay", iso3: "PRY", code: "+595" },
  { country: "Peru", iso3: "PER", code: "+51" },
  { country: "Philippines", iso3: "PHL", code: "+63" },
  { country: "Poland", iso3: "POL", code: "+48" },
  { country: "Portugal", iso3: "PRT", code: "+351" },

  { country: "Qatar", iso3: "QAT", code: "+974" },

  { country: "Romania", iso3: "ROU", code: "+40" },
  { country: "Russia", iso3: "RUS", code: "+7" },
  { country: "Rwanda", iso3: "RWA", code: "+250" },

  { country: "Saudi Arabia", iso3: "SAU", code: "+966" },
  { country: "Senegal", iso3: "SEN", code: "+221" },
  { country: "Serbia", iso3: "SRB", code: "+381" },
  { country: "Singapore", iso3: "SGP", code: "+65" },
  { country: "Slovakia", iso3: "SVK", code: "+421" },
  { country: "Slovenia", iso3: "SVN", code: "+386" },
  { country: "South Africa", iso3: "ZAF", code: "+27" },
  { country: "South Korea", iso3: "KOR", code: "+82" },
  { country: "Spain", iso3: "ESP", code: "+34" },
  { country: "Sri Lanka", iso3: "LKA", code: "+94" },
  { country: "Sudan", iso3: "SDN", code: "+249" },
  { country: "Sweden", iso3: "SWE", code: "+46" },
  { country: "Switzerland", iso3: "CHE", code: "+41" },
  { country: "Syria", iso3: "SYR", code: "+963" },

  { country: "Taiwan", iso3: "TWN", code: "+886" },
  { country: "Tanzania", iso3: "TZA", code: "+255" },
  { country: "Thailand", iso3: "THA", code: "+66" },
  { country: "Tunisia", iso3: "TUN", code: "+216" },
  { country: "Turkey", iso3: "TUR", code: "+90" },

  { country: "Uganda", iso3: "UGA", code: "+256" },
  { country: "Ukraine", iso3: "UKR", code: "+380" },
  { country: "United Arab Emirates", iso3: "ARE", code: "+971" },
  { country: "United Kingdom", iso3: "GBR", code: "+44" },
  { country: "United States", iso3: "USA", code: "+1" },
  { country: "Uruguay", iso3: "URY", code: "+598" },
  { country: "Uzbekistan", iso3: "UZB", code: "+998" },

  { country: "Venezuela", iso3: "VEN", code: "+58" },
  { country: "Vietnam", iso3: "VNM", code: "+84" },

  { country: "Yemen", iso3: "YEM", code: "+967" },

  { country: "Zambia", iso3: "ZMB", code: "+260" },
  { country: "Zimbabwe", iso3: "ZWE", code: "+263" }

];
